services:
  dwz-server:
    image: docker.cnb.cool/mliev/open/dwz-server:latest
    restart: always
    ports:
      - ${HOST_IP}:${HTTP_PORT}:8080
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
    volumes:
      - ${APP_PATH}/data/config/:/app/config/
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true